[build]
builder = "nixpacks"

[deploy]
startCommand = "python init_database.py && gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
