[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:${PORT:-8000} --workers 1 --timeout 120 --access-logfile - --error-logfile -"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
